FEATURES:
  add_embs: true
  add_eweights: true
  add_fudge: false
  add_geom: true
  add_hist: true
  add_visual: false
  num_polar_bins: 8
GRAPHS:
  data_type: pdf
  edge_type: knn
  node_granularity: ocr
LOADER:
  src_data: DocLayNet
